/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ComboItemController;
import Controllers.DB;
import Controllers.ExpenseController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anchor
 */
public class AddExpenseView extends javax.swing.JFrame {
        
    private static ExpenseController expenseController;
    public AddExpenseView() {
        initComponents();
        expenseController = new ExpenseController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAmount = new javax.swing.JTextField();
        lblAmount = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        chkRecurring = new javax.swing.JCheckBox();
        btnAddExpense = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        cbxFrequency = new javax.swing.JComboBox<>();
        lblFrequency = new javax.swing.JLabel();
        cbxCategory = new javax.swing.JComboBox<>();
        lblCategory = new javax.swing.JLabel();
        scrlNote = new javax.swing.JScrollPane();
        txtaNote = new javax.swing.JTextArea();
        lblEndDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dtpStartDate = new org.jdesktop.swingx.JXDatePicker();
        dtpEndDate = new org.jdesktop.swingx.JXDatePicker();

        setTitle("Add New Expense");
        setName("frmAddExpense"); // NOI18N

        txtAmount.setName("txtAmount"); // NOI18N

        lblAmount.setText("Amount:");
        lblAmount.setName("lblAmount"); // NOI18N

        lblDate.setText("Date:");

        chkRecurring.setText("Recurring Expense?");
        chkRecurring.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        chkRecurring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkRecurringActionPerformed(evt);
            }
        });

        btnAddExpense.setText("Add Expense");
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseActionPerformed(evt);
            }
        });

        btnHome.setLabel("Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        cbxFrequency.setMaximumRowCount(5);
        cbxFrequency.setEnabled(false);
        cbxFrequency.setFocusable(false);
        cbxFrequency.setOpaque(false);

        lblFrequency.setText("Frequency:");
        lblFrequency.setEnabled(false);
        lblFrequency.setName("lblFrequency"); // NOI18N
        lblFrequency.setOpaque(true);

        lblCategory.setText("Category:");

        txtaNote.setColumns(20);
        txtaNote.setRows(5);
        txtaNote.setText(" ");
        scrlNote.setViewportView(txtaNote);

        lblEndDate.setText("End Date:");
        lblEndDate.setEnabled(false);

        jLabel1.setText("Note:");

        dtpEndDate.setEnabled(false);

        DB db = new DB();
        ResultSet rs = db.getFrequencies();
        try {
            while (rs.next()) {
                cbxFrequency.addItem(new ComboItemController(rs.getInt("ID"), rs.getString("Name")).toString());
            }   } catch (SQLException ex) {
                Logger.getLogger(IncomeView.class.getName()).log(Level.SEVERE, null, ex);
            }
            rs = db.getCategories(2);   // 1 for income categories, 2 for expense categories
            try {
                while (rs.next()) {
                    cbxCategory.addItem(new ComboItemController(rs.getInt("ID"), rs.getString("Name")).toString());
                }   } catch (SQLException ex) {
                    Logger.getLogger(IncomeView.class.getName()).log(Level.SEVERE, null, ex);
                }

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddExpense, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(chkRecurring)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dtpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEndDate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dtpEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(scrlNote, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                );
                layout.setVerticalGroup(
                    layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAmount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(lblEndDate)
                            .addComponent(dtpStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtpEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chkRecurring)
                            .addComponent(cbxFrequency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFrequency))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCategory))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrlNote, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddExpense)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHome)
                        .addContainerGap())
                );

                dtpStartDate.getEditor().setEditable(false);
                dtpEndDate.getEditor().setEditable(false);

                pack();
            }// </editor-fold>//GEN-END:initComponents
 

           
    private void chkRecurringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkRecurringActionPerformed
        //ENABLE/DISABLE LABEL AND FREQUENCY CBX
        if(chkRecurring.isSelected()){
            lblFrequency.setEnabled(true);
            cbxFrequency.setEnabled(true);
            lblEndDate.setEnabled(true);
            dtpEndDate.setEnabled(true);
        }
        else{
            lblFrequency.setEnabled(false);
            cbxFrequency.setEnabled(false);
            lblEndDate.setEnabled(false);
            dtpEndDate.setEnabled(false);
        }

    }//GEN-LAST:event_chkRecurringActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        //expenseController.showMainPage();
        expenseController.closeAddExpenseView();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseActionPerformed
        if(expenseController.validateFields()){
        expenseController.processNewExpense();
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid input when saving Expense.");
        }
    }//GEN-LAST:event_btnAddExpenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddExpenseView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddExpenseView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnHome;
    private javax.swing.JComboBox<String> cbxCategory;
    private javax.swing.JComboBox<String> cbxFrequency;
    private javax.swing.JCheckBox chkRecurring;
    private org.jdesktop.swingx.JXDatePicker dtpEndDate;
    private org.jdesktop.swingx.JXDatePicker dtpStartDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblFrequency;
    private javax.swing.JScrollPane scrlNote;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextArea txtaNote;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnAddExpense() {
        return btnAddExpense;
    }

    public void setBtnAddExpense(javax.swing.JButton btnAddExpense) {
        this.btnAddExpense = btnAddExpense;
    }

    public javax.swing.JButton getBtnHome() {
        return btnHome;
    }

    public void setBtnHome(javax.swing.JButton btnHome) {
        this.btnHome = btnHome;
    }

    public javax.swing.JComboBox<String> getCbxCategory() {
        return cbxCategory;
    }

    public void setCbxCategory(javax.swing.JComboBox<String> cbxCategory) {
        this.cbxCategory = cbxCategory;
    }

    public javax.swing.JComboBox<String> getCbxFrequency() {
        return cbxFrequency;
    }

    public void setCbxFrequency(javax.swing.JComboBox<String> cbxFrequency) {
        this.cbxFrequency = cbxFrequency;
    }

    public javax.swing.JCheckBox getChkRecurring() {
        return chkRecurring;
    }

    public void setChkRecurring(javax.swing.JCheckBox chkRecurring) {
        this.chkRecurring = chkRecurring;
    }

    public org.jdesktop.swingx.JXDatePicker getDtpStartDate() {
        return dtpStartDate;
    }

    public void setDtpDate(org.jdesktop.swingx.JXDatePicker dtpStartDate) {
        this.dtpStartDate = dtpStartDate;
    }

//    public javax.swing.JLabel getLblHeader() {
//        return lblHeader;
//    }
//
//    public void setLblHeader(javax.swing.JLabel lblHeader) {
//        this.lblHeader = lblHeader;
//    }

    public javax.swing.JTextField getTxtAmount() {
        return txtAmount;
    }

    public void setTxtAmount(javax.swing.JTextField txtExpense) {
        this.txtAmount = txtExpense;
    }

    public javax.swing.JTextArea getTxtaNote() {
        return txtaNote;
    }

    public void setTxtaNote(javax.swing.JTextArea txtaNote) {
        this.txtaNote = txtaNote;
    }

    public org.jdesktop.swingx.JXDatePicker getDtpEndDate() {
        return dtpEndDate;
    }

    public void setDtpEndDate(org.jdesktop.swingx.JXDatePicker dtpEndDate) {
        this.dtpEndDate = dtpEndDate;
    }
}
