/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.GoalController;
import Controllers.IncomeController;
import Controllers.LimitController;
import Models.MyDefaultTableModel;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.JTable;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.MatteBorder;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author johnsonjm
 */
public class IncomeView extends javax.swing.JFrame {
    private IncomeController incomeController;
    private static LimitController limitController;
    private static GoalController goalController;
    
    public IncomeView() {
        initComponents();
        incomeController = new IncomeController();
        limitController = new LimitController();
        goalController = new GoalController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tblIncome = new JTable(){
            private Border outside = new MatteBorder(1, 0, 1, 0, Color.RED);
            private Border inside = new EmptyBorder(0, 1, 0, 1);
            private Border highlight = new CompoundBorder(outside, inside);

            public Component prepareRenderer(TableCellRenderer renderer, int row, int column)
            {
                Component c = super.prepareRenderer(renderer, row, column);
                JComponent jc = (JComponent)c;
                // Add a border to the selected row

                if (isRowSelected(row) && isCellEditable(row, 1))
                jc.setBorder( highlight );

                return c;
            }
        };
        btnAddIncome = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        lblCurrentIncome = new javax.swing.JLabel();
        btnAddIncomeGoal = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setTitle("Income");
        setName("frmIncome"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(655, 575));

        scrollPane.setBorder(null);
        scrollPane.setName("scrollPane"); // NOI18N

        tblIncome.setBackground(new java.awt.Color(240, 240, 240));
        tblIncome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tblIncome.setModel(new MyDefaultTableModel(30,7));
        tblIncome.setToolTipText("Income Table");
        tblIncome.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        tblIncome.setName("tblIncome"); // NOI18N
        tblIncome.addKeyListener(new KeyAdapter() {
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                    //               IncomeController.editRecord();
                }
            }
        });
        scrollPane.setViewportView(tblIncome);

        btnAddIncome.setText("Add Income");
        btnAddIncome.setMaximumSize(new java.awt.Dimension(110, 30));
        btnAddIncome.setMinimumSize(new java.awt.Dimension(110, 30));
        btnAddIncome.setName("btnAddIncome"); // NOI18N
        btnAddIncome.setPreferredSize(new java.awt.Dimension(110, 30));
        btnAddIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIncomeActionPerformed(evt);
            }
        });

        btnHome.setText("Home");
        btnHome.setMaximumSize(new java.awt.Dimension(110, 30));
        btnHome.setMinimumSize(new java.awt.Dimension(110, 30));
        btnHome.setName("btnHome"); // NOI18N
        btnHome.setPreferredSize(new java.awt.Dimension(110, 30));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeClick(evt);
            }
        });

        lblCurrentIncome.setBackground(new java.awt.Color(0, 241, 0));
        lblCurrentIncome.setForeground(new java.awt.Color(0, 1, 0));
        lblCurrentIncome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCurrentIncome.setText("Area to display total income");
        lblCurrentIncome.setName("lblCurrentIncome"); // NOI18N

        btnAddIncomeGoal.setText("Add Income Goal");
        btnAddIncomeGoal.setName("btnAddIncomeGoal"); // NOI18N
        btnAddIncomeGoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIncomeGoalActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Record");
        btnEdit.setName("btnEdit"); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete Record");
        btnDelete.setName("btnDelete"); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
            .addComponent(lblCurrentIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddIncomeGoal, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCurrentIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddIncomeGoal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeClick
        // TODO add your handling code here:
        incomeController.returnToMainPage();
    }//GEN-LAST:event_btnHomeClick

    private void btnAddIncomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIncomeActionPerformed
        incomeController.showAddIncomeView();
    }//GEN-LAST:event_btnAddIncomeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        incomeController.startTableEdit();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        incomeController.deleteRecord();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddIncomeGoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIncomeGoalActionPerformed
        goalController.addIncomeGoal();
    }//GEN-LAST:event_btnAddIncomeGoalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncomeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIncome;
    private javax.swing.JButton btnAddIncomeGoal;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JLabel lblCurrentIncome;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblIncome;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLblCurrentIncome() {
        return lblCurrentIncome;
    }

    public void setLblCurrentIncome(javax.swing.JLabel lblCurrentIncome) {
        this.lblCurrentIncome = lblCurrentIncome;
    }

    public javax.swing.JTable getTblIncome() {
        return tblIncome;
    }

    public void setTblIncome(javax.swing.JTable tblIncome) {
        this.tblIncome = tblIncome;
    }
}
