/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.DB;
import Controllers.Helper;
import Controllers.LoginController;
import Controllers.UserController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anchor
 */
public class LoginView extends javax.swing.JFrame {
    private LoginController loginController = new LoginController();
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        lblNewPassword = new javax.swing.JLabel();
        lblNewUsername = new javax.swing.JLabel();
        txtNewUsername = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        pnlButtons = new javax.swing.JPanel();
        btnRegister = new javax.swing.JToggleButton();
        btnLogin = new javax.swing.JButton();
        btnRemoveUser = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        pwdPassword = new javax.swing.JPasswordField();
        pwdNewPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(485, 350));
        setMinimumSize(new java.awt.Dimension(485, 350));
        setPreferredSize(new java.awt.Dimension(485, 350));
        setResizable(false);
        setSize(new java.awt.Dimension(485, 350));

        lblHeader.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Expense Tracker Login");

        lblFullName.setText("Full Name");

        txtFullName.setMinimumSize(new java.awt.Dimension(170, 20));
        txtFullName.setPreferredSize(new java.awt.Dimension(170, 20));

        lblNewPassword.setText("Enter Password");

        lblNewUsername.setText("New Username");

        txtNewUsername.setMinimumSize(new java.awt.Dimension(170, 20));
        txtNewUsername.setPreferredSize(new java.awt.Dimension(170, 20));

        lblUserName.setText("Enter Username");

        txtUsername.setMinimumSize(new java.awt.Dimension(170, 20));
        txtUsername.setPreferredSize(new java.awt.Dimension(170, 20));

        lblPassword.setText("Enter Password");

        pnlButtons.setMaximumSize(new java.awt.Dimension(445, 120));
        pnlButtons.setMinimumSize(new java.awt.Dimension(445, 40));
        pnlButtons.setPreferredSize(new java.awt.Dimension(445, 120));

        btnRegister.setText("Register New User");
        btnRegister.setMaximumSize(new java.awt.Dimension(445, 25));
        btnRegister.setMinimumSize(new java.awt.Dimension(445, 25));
        btnRegister.setPreferredSize(new java.awt.Dimension(445, 25));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        pnlButtons.add(btnRegister);

        btnLogin.setText("Login");
        btnLogin.setMaximumSize(new java.awt.Dimension(445, 25));
        btnLogin.setMinimumSize(new java.awt.Dimension(445, 25));
        btnLogin.setPreferredSize(new java.awt.Dimension(445, 25));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        pnlButtons.add(btnLogin);

        btnRemoveUser.setText("Remove User");
        btnRemoveUser.setMaximumSize(new java.awt.Dimension(445, 25));
        btnRemoveUser.setMinimumSize(new java.awt.Dimension(445, 25));
        btnRemoveUser.setPreferredSize(new java.awt.Dimension(445, 25));
        btnRemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveUserActionPerformed(evt);
            }
        });
        pnlButtons.add(btnRemoveUser);

        btnClose.setText("Close");
        btnClose.setMaximumSize(new java.awt.Dimension(445, 25));
        btnClose.setMinimumSize(new java.awt.Dimension(445, 25));
        btnClose.setPreferredSize(new java.awt.Dimension(445, 25));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlButtons.add(btnClose);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUserName)
                                .addGap(18, 18, 18)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNewPassword)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblFullName)
                                        .addComponent(lblNewUsername)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNewUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pwdNewPassword)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassword)
                                .addGap(18, 18, 18)
                                .addComponent(pwdPassword)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lblHeader)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewUsername))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFullName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pwdNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNewPassword, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(pnlButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if(this.getBtnRegister().isSelected()){
            //register new user and login
                String userName = this.getTxtNewUsername().getText();
                String password = this.getPwdNewPassword().getText();
                String name = this.getTxtFullName().getText();
                if(loginController.validateFields(userName, password, name)){
 
                DB db = new DB();
                db.addUser(userName, password, name);
                loginController.loginUser(userName, password, this);
                // this.setVisible(false);
            }
            else{
                JOptionPane.showMessageDialog(this, "Invalid Credentials");
            }
        }
        else{
            //login existing user
                String userName = this.getTxtUsername().getText();
                String password = this.getPwdPassword().getText();
        if(loginController.validateFields(userName, password)){

                loginController.loginUser(userName, password, this);
            }  
            else{
                JOptionPane.showMessageDialog(this, "Invalid Credentials");
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        //make labels and txtboxes visible
        if(this.getBtnRegister().isSelected()){
        this.getLblUserName().setVisible(false);
        this.getLblPassword().setVisible(false);
        this.getTxtUsername().setVisible(false);
        this.getPwdPassword().setVisible(false);
        this.getLblFullName().setVisible(true);
        this.getTxtFullName().setVisible(true);
        this.getLblNewUsername().setVisible(true);
        this.getTxtNewUsername().setVisible(true);
        this.getLblNewPassword().setVisible(true);
        this.getPwdNewPassword().setVisible(true);
        }
        else{
        this.getLblUserName().setVisible(true);
        this.getLblPassword().setVisible(true);
        this.getTxtUsername().setVisible(true);
        this.getPwdPassword().setVisible(true);
        this.getLblFullName().setVisible(false);
        this.getTxtFullName().setVisible(false);
        this.getLblNewUsername().setVisible(false);
        this.getTxtNewUsername().setVisible(false);
        this.getLblNewPassword().setVisible(false);
        this.getPwdNewPassword().setVisible(false);
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnRemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveUserActionPerformed
        if(this.getBtnRegister().isSelected()){
            JOptionPane.showMessageDialog(this, "Register Button cannot be selected when deleting a user.");
        }
        else{ //Must be a valid user to remove user
                String userName = this.getTxtUsername().getText();
                String password = this.getPwdPassword().getText();
                if(loginController.validateFields(userName, password)){

                //loginController.loginUser(userName, password, this);
                DB db = new DB();
                try {
                    UserController user = new UserController(db.getUser(userName, password));
                    if(user.validUser){
                        int reply = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete user "+userName +" ?");
                        if(reply == JOptionPane.YES_OPTION){
                             db.removeUser(user.userID);
                             JOptionPane.showMessageDialog(this, userName + "deleted.");
                        }
                        //POSSIBLY CLEAR FIELDS HERE?
                        
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }  
            else{
                JOptionPane.showMessageDialog(this, "Invalid Credentials");
            }        
        }
    }//GEN-LAST:event_btnRemoveUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLogin;
    private javax.swing.JToggleButton btnRegister;
    private javax.swing.JButton btnRemoveUser;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblNewPassword;
    private javax.swing.JLabel lblNewUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPasswordField pwdNewPassword;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtNewUsername;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JButton getBtnLogin() {
        return btnLogin;
    }

    public void setBtnLogin(javax.swing.JButton btnLogin) {
        this.btnLogin = btnLogin;
    }

    public javax.swing.JToggleButton getBtnRegister() {
        return btnRegister;
    }

    public void setBtnRegister(javax.swing.JToggleButton btnRegister) {
        this.btnRegister = btnRegister;
    }

    public javax.swing.JLabel getLblFullName() {
        return lblFullName;
    }

    public void setLblFullName(javax.swing.JLabel lblFullName) {
        this.lblFullName = lblFullName;
    }

    public javax.swing.JLabel getLblNewPassword() {
        return lblNewPassword;
    }

    public void setLblNewPassword(javax.swing.JLabel lblNewPassword) {
        this.lblNewPassword = lblNewPassword;
    }

    public javax.swing.JLabel getLblNewUsername() {
        return lblNewUsername;
    }

    public void setLblNewUsername(javax.swing.JLabel lblNewUsername) {
        this.lblNewUsername = lblNewUsername;
    }

    public javax.swing.JLabel getLblPassword() {
        return lblPassword;
    }

    public void setLblPassword(javax.swing.JLabel lblPassword) {
        this.lblPassword = lblPassword;
    }

    public javax.swing.JLabel getLblUserName() {
        return lblUserName;
    }

    public void setLblUserName(javax.swing.JLabel lblUserName) {
        this.lblUserName = lblUserName;
    }

    public javax.swing.JTextField getTxtFullName() {
        return txtFullName;
    }

    public void setTxtFullName(javax.swing.JTextField txtFullName) {
        this.txtFullName = txtFullName;
    }

    public javax.swing.JTextField getPwdNewPassword() {
        return pwdNewPassword;
    }

    public void setPwdNewPassword(javax.swing.JPasswordField pwdNewPassword) {
        this.pwdNewPassword = pwdNewPassword;
    }

    public javax.swing.JTextField getTxtNewUsername() {
        return txtNewUsername;
    }

    public void setTxtNewUsername(javax.swing.JTextField txtNewUsername) {
        this.txtNewUsername = txtNewUsername;
    }

    public javax.swing.JTextField getPwdPassword() {
        return pwdPassword;
    }

    public void setPwdPassword(javax.swing.JPasswordField pwdPassword) {
        this.pwdPassword = pwdPassword;
    }

    public javax.swing.JTextField getTxtUsername() {
        return txtUsername;
    }

    public void setTxtUsername(javax.swing.JTextField txtUsername) {
        this.txtUsername = txtUsername;
    }

//    public javax.swing.JPanel getPnlLogin() {
//        return pnlLogin;
//    }
//
//    public void setPnlLogin(javax.swing.JPanel pnlLogin) {
//        this.pnlLogin = pnlLogin;
//    }
//
//    public javax.swing.JPanel getPnlRegister() {
//        return pnlRegister;
//    }
//
//    public void setPnlRegister(javax.swing.JPanel pnlRegister) {
//        this.pnlRegister = pnlRegister;
//    }
}
