/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.ExpenseController;
import Controllers.ExportController;
import Controllers.GoalController;
import Controllers.IncomeController;
import Controllers.LimitController;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author johnsonjm
 */
public class MainPageView extends javax.swing.JFrame {
    private static IncomeController incomeController;
    private static ExpenseController expenseController;
    private static ExportController exportController;
    /**
     * Creates new form MainPage
     */
    public MainPageView() {
        initComponents();
        incomeController = new IncomeController();
        expenseController = new ExpenseController();
        exportController = new ExportController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblWarnings = new javax.swing.JLabel();
        pnlGraph = new javax.swing.JPanel();
        lblGraph = new javax.swing.JLabel();
        pnlButtonsPanel = new javax.swing.JPanel();
        btnExportData = new javax.swing.JButton();
        btnAddExpense = new javax.swing.JButton();
        btnAddIncome = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblBalance = new javax.swing.JLabel();
        lblGoalsBanner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expense Tracker");
        setName("frmMain"); // NOI18N
        setSize(new java.awt.Dimension(450, 600));

        lblWarnings.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblWarnings.setForeground(new java.awt.Color(255, 0, 0));
        lblWarnings.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblWarnings.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblWarnings.setName("lblWarnings"); // NOI18N

        pnlGraph.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlGraph.setToolTipText("Area for the Pie Graph breakdown of expenses BY CATEGORY");
        pnlGraph.setName("pnlGraph"); // NOI18N
        pnlGraph.setPreferredSize(new java.awt.Dimension(400, 175));

        lblGraph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGraph.setText("Area for Pie Chart to breakdown expenses by Category");
        pnlGraph.add(lblGraph);

        btnExportData.setText("Export Data");
        btnExportData.setToolTipText("Export Data");
        btnExportData.setName("btnExportData"); // NOI18N
        btnExportData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportDataActionPerformed(evt);
            }
        });

        btnAddExpense.setText("Expenses");
        btnAddExpense.setToolTipText("Add Expense");
        btnAddExpense.setName("btnAddExpense"); // NOI18N
        btnAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddExpenseClick(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsPanelLayout = new javax.swing.GroupLayout(pnlButtonsPanel);
        pnlButtonsPanel.setLayout(pnlButtonsPanelLayout);
        pnlButtonsPanelLayout.setHorizontalGroup(
            pnlButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExportData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAddExpense, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );
        pnlButtonsPanelLayout.setVerticalGroup(
            pnlButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsPanelLayout.createSequentialGroup()
                .addComponent(btnAddExpense)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExportData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddIncome.setText("Income");
        btnAddIncome.setToolTipText("Add Income");
        btnAddIncome.setName("btnAddIncome"); // NOI18N
        btnAddIncome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIncomeClick(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.setToolTipText("Close");
        btnClose.setName("btnClose"); // NOI18N
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseClick(evt);
            }
        });

        lblBalance.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lblBalance.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalance.setText("Area for Balance");
        lblBalance.setToolTipText("Balance");

        lblGoalsBanner.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGoalsBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGoalsBanner.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblWarnings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                    .addComponent(btnAddIncome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblGoalsBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblWarnings, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblGoalsBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddIncome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblWarnings.getAccessibleContext().setAccessibleName("Warning Banner");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddIncomeClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIncomeClick
        // TODO add your handling code here:
        incomeController.showIncomeView();
    }//GEN-LAST:event_btnAddIncomeClick

    private void btnAddExpenseClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddExpenseClick
        // TODO add your handling code here:
        expenseController.showExpenseView();
    }//GEN-LAST:event_btnAddExpenseClick

    private void btnCloseClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseClick
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCloseClick

    private void btnExportDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportDataActionPerformed
        exportController.showExportDataView();
    }//GEN-LAST:event_btnExportDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPageView().setVisible(true);
            }
        });
    }
    
    public MainPageView getMainPageView(){
        return this;
    }

    public JLabel getLblGraph() {
        return lblGraph;
    }

    public void setLblGraph(JLabel lblGraph) {
        this.lblGraph = lblGraph;
    }

    public JLabel getLblWarnings() {
        return lblWarnings;
    }

    public void setLblWarnings(JLabel lblWarnings) {
        this.lblWarnings = lblWarnings;
    }

    public JPanel getPnlGraph() {
        return pnlGraph;
    }

    public void setPnlGraph(JPanel pnlGraph) {
        this.pnlGraph = pnlGraph;
    }
    
    public javax.swing.JLabel getLblBalance() {
        return lblBalance;
    }

    public void setLblBalance(javax.swing.JLabel lblBalance) {
        this.lblBalance = lblBalance;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddExpense;
    private javax.swing.JButton btnAddIncome;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExportData;
    private javax.swing.JLabel lblBalance;
    private javax.swing.JLabel lblGoalsBanner;
    private javax.swing.JLabel lblGraph;
    private javax.swing.JLabel lblWarnings;
    private javax.swing.JPanel pnlButtonsPanel;
    private javax.swing.JPanel pnlGraph;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getLblGoalsBanner() {
        return lblGoalsBanner;
    }

    public void setLblGoalsBanner(javax.swing.JLabel lblGoalsBanner) {
        this.lblGoalsBanner = lblGoalsBanner;
    }


}
